### ISSUE TITLE
use in phoenix compile error

### ISSUE THREAD

**Issue by AndwareSsj** [elixir-maru/maru_swagger#14]
error stack:
```
== Compilation error on file web/views/layout_view.ex ==
** (CompileError) web/views/layout_view.ex:2: module PhoenixMaru.Router.Helpers is not loaded and could not be found
    (phoenix_maru) expanding macro: PhoenixMaru.Web.__using__/1
    web/views/layout_view.ex:2: PhoenixMaru.LayoutView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/layout_view.ex:2: PhoenixMaru.LayoutView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

this is my code

```
defmodule PhoenixMaru.Api.Router do
  use Maru.Router, make_plug: true
  use MaruSwagger

  swagger at:         "/swagger",      # (required) the mount point for the URL
            pretty:     true,            # (optional) the environments swagger works
            except:     [:prod],         # (optional) the environments swagger NOT works
            force_json: true           # (optional) force JSON for all params instead of formData

  get do
    text conn, "API works!"
  end

  mount PhoenixMaru.Api.UserApi
end

```

I remove swagger config and make it. it's successfully. but use swagger config failed

**Comment by falood** [comment]
Hi @AndwareSsj 
That's a compile time bug.
Before I fix it and release new version, you can use such code to make your code works.
```
  swagger at: "/swagger",
            pretty: true,
            except: [:prod],
            force_json: true,
            swagger_inject: [basePath: "/"]
```

Thank you for using maru and pointing it out!

**Comment by AndwareSsj** [comment]
@falood thanks
